name: CI

on: [push, pull_request]

env:
  # Default command; individual squads can override in repo Variables
  TEST_CMD: npm test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node setup is harmless for other languages (adds <1 min)
      - name: Set up Node 18 (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Try install; ignore failure for non‑npm stacks
      - name: Install npm deps (skip on other stacks)
        run: npm ci || true

      - name: Run test command
        run: ${{ env.TEST_CMD }}
